name: flaviolamenza
favicon: null
layout_spectrum: 0.3900513695552945
typography_spectrum: 0.4187390806619078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5929207277949899
  lightness: 0.3751870193518698
  saturation: 0.8862140774726868
  rhythmicContrast: 0.6363121294416487
purpose: []
