name: flaviolamenza
favicon: null
layout_spectrum: 0.23839
typography_spectrum: 0.65698
title: 'Photographer and Filmmaker, Flavio Lamenza Portfolio`s'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#08090e'
    - '#363844'
    - '#774b0e'
    - '#812310'
    - '#6090d0'
  brandStrength: 0.5
  lightness: 0.3751870193518698
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
