name: flaviolamenza
favicon: null
layout_spectrum: 0.23839
typography_spectrum: 0.65698
title: 'Photographer and Filmmaker, Flavio Lamenza Portfolio`s'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a88452'
    - '#0f0c07'
    - '#533b2f'
    - '#89c3ad'
  brandStrength: 0.5
  lightness: 0.3751870193518698
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
